### ISSUE TITLE
iTween on OpenUPM

### ISSUE THREAD

**Issue by favoyang** [route1rodent/iTween#1]
Hi @route1rodent,

Thanks for creating the amazing project. I'm the creator of [OpenUPM](https://openupm.com), a public upm registry with automatic build pipelines that publish new package bundle based on valid git tags. You can read [the announcement](https://www.patreon.com/posts/openupm-beta-is-32544176) to get the basic idea, so far it hosts 80+ packages as of December 2019.

I have included the package to the service.
https://openupm.com/packages/com.pixelplacement.itween/

If you feel interesting, you can also explore to [add a badge](https://openupm.com/docs/adding-badge.html) to README:

[![openupm](https://img.shields.io/npm/v/com.pixelplacement.itween?label=openupm&registry_uri=https://package.openupm.com)](https://openupm.com/packages/com.pixelplacement.itween/)

Feel free to ask me questions or close the issue.

**Comment by route1rodent** [comment]
hey @favoyang that's cool!
I was missing a tool like this, that can be like npm but for Unity

I will include the badge soon

**Comment by favoyang** [comment]
@route1rodent great. Here’s an example readme file: https://github.com/hajimeku/ServiceLocator/blob/master/README.md

**Comment by favoyang** [comment]
@route1rodent I created a PR for this task. see #2

**Comment by route1rodent** [comment]
thank you! then I'll close this ticktet
